AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-serverless-sam-app

  Sample SAM Template for aws-serverless-sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:

  # Lambda Layer for the Lambda functions
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda-layer
      CompatibleRuntimes:
        - java11
    Metadata:
      BuildMethod: java11

  # DynamoDB table
  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      AttributeDefinitions:
        - AttributeName: isbn
          AttributeType: S
      KeySchema:
        - AttributeName: isbn
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  #Lambda functions
  PutItemHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: put-item-service
      Handler: com.nva.PutItemHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /books
            Method: post
      Layers:
        - Ref: MyLayer

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PutItemHandlerApi:
    Description: "API Gateway endpoint URL for Prod stage for PutItemHandler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
  PutItemHandlerFunction:
    Description: "PutItemHandler Lambda Function ARN"
    Value: !GetAtt PutItemHandlerFunction.Arn
  PutItemHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for PutItemHandler function"
    Value: !GetAtt PutItemHandlerFunctionRole.Arn
